import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import blogApi from "./api/blogApi";
import { useState, useEffect } from "react";
import { Default } from "../componets/Default";

export default function Home({ posts, categories }) {
  const path = posts.path;
  const [catValue, setCatValue] = useState("");
  const [postList, setPostList] = useState(posts.posts);
  const [postListCat, setPostListCat] = useState(null);
  const sanityIoImageLoader = ({ src, width, quality }) => {
    return `https://cdn.sanity.io/${src}?w=${width}&q=${quality || 75}`;
  };
  useEffect(() => {
    const getSingle = async () => {
      if (catValue !== "") {
        const newCat = await blogApi.getSingleCategory(catValue);
        setPostListCat(newCat.posts);
      } else if (catValue === "") {
        setPostListCat(null);
      }
    };
    getSingle();
  }, [catValue]);

  return (
    <Default>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <select value={catValue} onChange={(e) => setCatValue(e.target.value)}>
        <option value="">Todos</option>
        {categories &&
          categories.map((item, k) => (
            <option key={k} value={item.id}>
              {item.name}
            </option>
          ))}
      </select>

      {postListCat === null && (
        <>
          {postList.map((item, k) => (
            <div className="posts" key={k}>
              <Link href={`/post/${item.id}`}>
                <a>
                  <h2>{item.title}</h2>
                </a>
              </Link>
              <strong>Categoria {item.category.name}</strong>
              <Image
                src={`${path}/${item.photos[0].url}`}
                alt=""
                width={720}
                height={410}
                quality={100}
                placeholder="blur"
                blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mPcXg8AAfMBOOg8T0oAAAAASUVORK5CYII="
              />
              <br />
            </div>
          ))}
        </>
      )}

      {postListCat && (
        <>
          {postListCat.map((item, k) => (
            <div className="posts" key={k}>
              <Link href={`/post/${item.id}`}>
                <a>
                  <h2>{item.title}</h2>
                </a>
              </Link>
              <br />
            </div>
          ))}
        </>
      )}
    </Default>
  );
}

export const getStaticProps = async () => {
  const posts = await blogApi.getPosts();
  const { categories } = await blogApi.getCategories();
  return {
    props: {
      posts,
      categories,
    },
    revalidate: 7200, //quando passa 2 horas e tem novo post ele faz a requesição
  };
};
